query getMultimediaByUser($id: String!){
  getMultimediaByUser(id: $id){
    id
    descripcion
    url
    formato
    tamano
    id_bucket
    usuario_creador_id
    etiquetas_relacionadas_ids
    tableros_agregados_ids
    created_at
    updated_at
  }
}
