query userById($id: Int!){
  userById (id: $id ) {
    id
    username
    firstName
    lastName
    correo
    profiles {
        	userId
        	countryId
        	fechaNacimiento
        	genero
        	foto
        	descripcion
        	edad
      }
  }
}
